### ISSUE TITLE
Code availability

### ISSUE THREAD

**Issue by robitalec** [tgelmi-candusso/Dynamic-connectivity-assessment-for-a-terrestrial-predator-in-a-metropolitan-region#1]
In the [Data Availability Statement](https://esajournals.onlinelibrary.wiley.com/doi/full/10.1002/fee.2633#open-research-section) of the published article:

> The data and code that support the findings of this study are openly available in Zenodo, at [http://doi.org/10.5281/zenodo.10419385](https://doi.org/10.5281/zenodo.10419385), reference number 10419385.

The Zenodo archive lists only one file (coyotes_steps_FEE_manuscript_forZenodoRepository.csv) and links to this GitHub repository where there is only a license file. 

Where is the code accompanying this article?

**Comment by tgelmi-candusso** [comment]
The code is up now.

**Comment by robitalec** [comment]
Thank you, much appreciated.
